title: "My World of Insights"
description: "Welcome! Explore my journey in data-driven insights and impactful projects. Let’s dive into the world of business analysis together!"
email: "Lama.juraisy@gmail.com"
social:
linkedin: https://linkedin.com/in/lamaaljuraisi
github: https://github.com/LamaJuraisi
baseurl: "/Portfolio" # Keep this if the repository is hosted as a subfolder
url: "https://lamajuraisi.github.io"
