title: "Lama's Portfolio"
description: "Business Analyst Portfolio showcasing projects and skills"
email: "your-email@example.com"
social:
  twitter: your-twitter-handle
  linkedin: your-linkedin-url
