title: "Lama's Portfolio"
description: "Showcasing projects and skills in business analysis."
email: "Lama.juraisy@gmail.com"
social:
  linkedin: https://linkedin.com/in/your-linkedin-url
  github: https://github.com/LamaJuraisi
