title: "Lama's Portfolio"
description: "Business Analyst Portfolio showcasing projects and skills"
email: "Lama.juraisy@gmail.com"
social:
  twitter: your-twitter-handle
  linkedin: your-linkedin-url
